project_id = "kzupylvyamjaaobongvm"

[functions.generate-conversation-title]
verify_jwt = true

[functions.generate-teacher-conversation-title]
verify_jwt = true

[functions.mia-student-chat]
verify_jwt = true

[functions.mia-teacher-chat]
verify_jwt = true

[functions.teacher-job-runner]
verify_jwt = false

[functions.job-runner]
verify_jwt = false

[functions.generate-deep-search-report]
verify_jwt = true

[functions.plan-lesson-with-mia]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.transcribe-lecture-live]
verify_jwt = false

[functions.process-lecture-transcript]
verify_jwt = false

[functions.edit-lecture-content]
verify_jwt = false

[functions.generate-lecture-thumbnail]
verify_jwt = false

[functions.compare-with-lesson-plan]
verify_jwt = false

[functions.send-class-announcement]
verify_jwt = true

[functions.generate-annotation-title]
verify_jwt = true

[functions.generate-annotation-tags]
verify_jwt = true

[functions.ai-text-formatting]
verify_jwt = true

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = false
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[functions.get-due-reviews]
verify_jwt = true

[functions.submit-review-feedback]
verify_jwt = true

[functions.get-student-dashboard-data]
verify_jwt = true

[functions.generate-quiz]
verify_jwt = true

[functions.create-annotation-from-report]
verify_jwt = true

[functions.generate-study-materials]
verify_jwt = true

[functions.get-teacher-dashboard-insights]
verify_jwt = true

[functions.upload-library-material]
verify_jwt = true

[functions.generate-lesson-plan]
verify_jwt = true

[functions.get-student-classes]
verify_jwt = true

[functions.auto-enroll-student]
verify_jwt = false

[functions.generate-internship-tags]
verify_jwt = true

[functions.autocomplete-locations]
verify_jwt = true

[functions.save-internship-session]
verify_jwt = true

[functions.generate-teacher-annotation-title]
verify_jwt = true

[functions.generate-teacher-annotation-tags]
verify_jwt = true

[functions.teacher-ai-text-formatting]
verify_jwt = true

[functions.validate-formatted-content]
verify_jwt = true

[functions.send-teacher-event-notification]
verify_jwt = false

[functions.send-class-event-notification]
verify_jwt = false

[functions.send-class-event-update-notification]
verify_jwt = false

[functions.send-class-event-cancellation-notification]
verify_jwt = false

[functions.send-class-event-date-change-notification]
verify_jwt = false

[functions.validate-teacher-code]
verify_jwt = true

[functions.generate-teacher-codes]
verify_jwt = true

[functions.generate-lecture-tags]
verify_jwt = true

[functions.generate-teacher-quiz]
verify_jwt = true

[functions.generate-teacher-flashcards]
verify_jwt = true