-- Add new column for modular material didático system
ALTER TABLE lectures 
ADD COLUMN IF NOT EXISTS material_didatico_v2 TEXT;

-- Add index for performance (only where column has data)
CREATE INDEX IF NOT EXISTS idx_lectures_material_v2 
ON lectures(id) 
WHERE material_didatico_v2 IS NOT NULL;

-- Add comment explaining the column
COMMENT ON COLUMN lectures.material_didatico_v2 IS 
'Pure Markdown material generated by material-didatico-generator edge function (independent modular system). Replaces JSON-based structured_content.material_didatico with cleaner Markdown format.';